name: AntiSafeCombatLog
version: ${project.version}
main: dev.demeng.ascl.AntiSafeCombatLog
api-version: 1.13
depend: [ WorldGuard,WorldEdit ]
author: Demeng
description: Allows players to PvP in safe zones if tagged.
website: https://demeng.dev/
